services:
  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/nginx.conf:ro
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "8080:80"

  backend:
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8000/health >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 12
    build:
      context: .
      dockerfile: promtok_backend/Dockerfile.railway
    # Ensure CPU-only runtime and fast reload in dev
    environment:
      - UVICORN_RELOAD=${UVICORN_RELOAD:-true}
      - FORCE_CPU_MODE=true
      - PREFERRED_DEVICE_TYPE=cpu
      - OPENROUTER_API_KEY=dev-placeholder
    # Remove GPU deploy config from base compose
    deploy: null

  doc-processor:
    build:
      context: .
      dockerfile: promtok_backend/Dockerfile.railway
    environment:
      - FORCE_CPU_MODE=true
      - PREFERRED_DEVICE_TYPE=cpu
    deploy: null

  cli:
    build:
      context: .
      dockerfile: promtok_backend/Dockerfile.railway
    environment:
      - FORCE_CPU_MODE=true
      - PREFERRED_DEVICE_TYPE=cpu
    deploy: null

  # Frontend dev can run via `npm run dev` outside Docker.
  # Nginx continues to serve built assets if you prefer dockerized frontend.
