app = "promtok"
primary_region = "jnb"   # matches your existing machines' region

[build]
  dockerfile = "promtok_backend/Dockerfile"

[env]
  # Force the app to listen on port 8080 (Fly's default)
  PORT = "8080"
  # Force CPU mode to avoid GPU dependencies
  FORCE_CPU_MODE = "true"
  PREFERRED_DEVICE_TYPE = "cpu"
  # Database will be set automatically by Fly Postgres
  # JWT_SECRET, OPENAI_API_KEY, etc. should be set as secrets

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    soft_limit = 80
    hard_limit = 100

  [[http_service.checks]]
    grace_period = "10s"
    interval = "15s"
    method = "get"
    path = "/healthz"
    timeout = "5s"

# Mount volumes if needed
[mounts]
  source = "promtok_data"
  destination = "/app/ai_researcher/data"

[mounts]
  source = "promtok_model_cache"
  destination = "/root/.cache/huggingface"

# Database attachment (you'll need to create this separately)
# fly postgres create --name promtok-pg --region jnb
# fly postgres attach promtok-pg --app promtok
