app = "promtok-frontend"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile.fly"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    soft_limit = 200
    hard_limit = 250
  [[http_service.checks]]
    grace_period = "5s"
    interval = "15s"
    method = "get"
    path = "/"
    timeout = "2s"
