app = "promtok-backend"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile.fly"

[env]
  # Point this to your frontend after you deploy it
  FRONTEND_URL = "https://promtok-frontend.fly.dev"
  # Add your CORS origins (comma-separated)
  CORS_ALLOWED_ORIGINS = "https://promtok-frontend.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    soft_limit = 80
    hard_limit = 100
  [[http_service.checks]]
    grace_period = "8s"
    interval = "15s"
    method = "get"
    path = "/health"
    timeout = "2s"
