name: Fly Deploy - Backend
on:
  push:
    paths:
      - "promtok_backend/**"
      - ".github/workflows/fly-backend.yml"
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c promtok_backend/fly.toml --remote-only --app promtok-backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
