name: Fly Deploy - Frontend
on:
  push:
    paths:
      - "promtok_frontend/**"
      - ".github/workflows/fly-frontend.yml"
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c promtok_frontend/fly.toml --remote-only --app promtok-frontend --build-arg VITE_API_HTTP_URL=https://promtok-backend.fly.dev
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
